name: Textureless FreshMobs
description: No Textures! PBR shader required.
author: Null [Joshua Miller]
input:
  format: raw
  auto-material: false
profiles:
- edition: java
  format: 8
  name: Textureless-FreshMobs-LabPbr-16x
  description: No Textures! PBR shader required.
  tags: 16x LabPBR
  encoding:
    format: lab-1.3
    height:
      sampler: average
    occlusion:
      sampler: average
    normal-x:
      sampler: average
    normal-y:
      sampler: average
    normal-z:
      sampler: average
  block-texture-size: 16
  item-texture-size: 16
  texture-scale: 0.5
  auto-generate-occlusion: false
  occlusion-quality: 0.1
  occlusion-power: 1
- edition: java
  format: 8
  name: Textureless-FreshMobs-LabPbr-32x
  description: No Textures! PBR shader required.
  tags: 32x LabPBR
  encoding:
    format: lab-1.3
    sampler: nearest
    height:
      sampler: bilinear
  block-texture-size: 32
  item-texture-size: 32
  texture-scale: 1
  auto-generate-occlusion: false
  occlusion-quality: 0.2
  occlusion-power: 1
- edition: java
  format: 8
  name: Textureless-FreshMobs-LabPbr-64x
  description: No Textures! PBR shader required.
  tags: 64x LabPBR
  encoding:
    format: lab-1.3
    sampler: bicubic
    color-red:
      sampler: nearest
    color-green:
      sampler: nearest
    color-blue:
      sampler: nearest
    metal:
      sampler: nearest
    f0:
      sampler: nearest
  block-texture-size: 64
  item-texture-size: 64
  texture-scale: 2
  auto-generate-occlusion: false
  occlusion-quality: 0.1
  occlusion-power: 1
- edition: java
  format: 8
  name: Textureless-FreshMobs-OldPbr-32x
  description: No Textures! PBR shader required.
  tags: 32x OldPBR
  encoding:
    format: old-pbr
    sampler: nearest
    height:
      sampler: bilinear
  block-texture-size: 32
  item-texture-size: 32
  texture-scale: 1
  auto-generate-occlusion: true
  bake-occlusion-to-color: true
  occlusion-quality: 0.1
  occlusion-power: 2
