name: Release
on:
  workflow_dispatch:
    inputs:
      release_notes:
        description: 'Release notes. (optional)'
        required: false
      publish_curseforge:
        description: 'Publish to CurseForge? true | false'
        default: 'true'
        required: false

jobs:
  prepare_release:
    name: Prepare Release
    runs-on: ubuntu-latest
    outputs:
      release_id: ${{ steps.create_release.outputs.id }}
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - run: echo -e "${{ github.event.inputs.release_notes }}" > release_notes.md
      - name: Create Release Draft
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.GITHUB_RUN_NUMBER }}
          release_name: Release ${{ env.GITHUB_RUN_NUMBER }}
          body_path: release_notes.md
          draft: true

  publish_labPbr_32x:
    name: Publish LabPbr-32x
    runs-on: ubuntu-latest
    needs: [prepare_release]
    env:
      release_filename: Textureless-LabPbr-32x-v${{ env.GITHUB_RUN_NUMBER }}.zip
    steps:
      - uses: actions/checkout@v2
      - name: Compile LabPbr-32x
        uses: null511/PixelGraph.GitHubAction@main
        with:
          profile: src/LabPbr-32x.pack.yml
          zip: ${{ env.release_filename }}
      - name: Release LabPbr-32x
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.prepare_release.outputs.upload_url }}
          asset_path: ./${{ env.release_filename }}
          asset_name: ${{ env.release_filename }}
          asset_content_type: application/zip
      - name: Publish LabPbr-32x to CurseForge
        uses: itsmeow/curseforge-upload@v3
        if: github.event.inputs.publish_curseforge == 'true'
        with:
          display_name: "LabPBR 32x v${{ env.GITHUB_RUN_NUMBER }}"
          file_path: ${{ env.release_filename }}
          changelog: "###Release ${{github.event.inputs.version}}\n\n${{ github.event.inputs.release_notes }}"
          release_type: "release"
          project_id: 469686
          game_endpoint: "minecraft"
          #game_versions: "Minecraft 1.18:1.18.1"
          game_versions: "9008,8857,8830,8516,8203,8152,8134,8056,8010,7892,7890,7675,7664,7469,7413,7361,7344,7318,7132,7107,7081"
          token: "${{ secrets.CF_API_TOKEN }}"

  publish_labPbr_64x:
    name: Publish LabPbr-64x
    runs-on: ubuntu-latest
    needs: [prepare_release]
    env:
      release_filename: Textureless-LabPbr-64x-v${{ env.GITHUB_RUN_NUMBER }}.zip
    steps:
      - uses: actions/checkout@v2
      - name: Compile LabPbr-64x
        uses: null511/PixelGraph.GitHubAction@main
        with:
          profile: src/LabPbr-64x.pack.yml
          zip: ${{ env.release_filename }}
      - name: Release LabPbr-64x
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.prepare_release.outputs.upload_url }}
          asset_path: ./${{ env.release_filename }}
          asset_name: ${{ env.release_filename }}
          asset_content_type: application/zip

  publish_labPbr_16x:
    name: Publish LabPbr-16x
    runs-on: ubuntu-latest
    needs: [prepare_release]
    env:
      release_filename: Textureless-LabPbr-16x-v${{ env.GITHUB_RUN_NUMBER }}.zip
    steps:
      - uses: actions/checkout@v2
      - name: Compile LabPbr-16x
        uses: null511/PixelGraph.GitHubAction@main
        with:
          profile: src/LabPbr-16x.pack.yml
          zip: ${{ env.release_filename }}
      - name: Release LabPbr-16x
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.prepare_release.outputs.upload_url }}
          asset_path: ./${{ env.release_filename }}
          asset_name: ${{ env.release_filename }}
          asset_content_type: application/zip

  publish_labBakedAO_32x:
    name: Publish LabBakedAO-32x
    runs-on: ubuntu-latest
    needs: [prepare_release]
    env:
      release_filename: Textureless-LabBakedAO-32x-v${{ env.GITHUB_RUN_NUMBER }}.zip
    steps:
      - uses: actions/checkout@v2
      - name: Compile LabBakedAO-32x
        uses: null511/PixelGraph.GitHubAction@main
        with:
          profile: src/LabBakedAO-32x.pack.yml
          zip: ${{ env.release_filename }}
      - name: Release LabBakedAO-32x
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.prepare_release.outputs.upload_url }}
          asset_path: ./${{ env.release_filename }}
          asset_name: ${{ env.release_filename }}
          asset_content_type: application/zip

  publish_oldPbr_32x:
    name: Publish OldPbr-32x
    runs-on: ubuntu-latest
    needs: [prepare_release]
    env:
      release_filename: Textureless-OldPbr-32x-v${{ env.GITHUB_RUN_NUMBER }}.zip
    steps:
      - uses: actions/checkout@v2
      - name: Compile OldPbr-32x
        uses: null511/PixelGraph.GitHubAction@main
        with:
          profile: src/OldPbr-32x.pack.yml
          zip: ${{ env.release_filename }}
      - name: Release OldPbr-32x
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.prepare_release.outputs.upload_url }}
          asset_path: ./${{ env.release_filename }}
          asset_name: ${{ env.release_filename }}
          asset_content_type: application/zip

  publish_rtx_32x:
    name: Publish RTX-32x
    runs-on: ubuntu-latest
    needs: [prepare_release]
    env:
      release_filename: Textureless-RTX-32x-v${{ env.GITHUB_RUN_NUMBER }}.zip
    steps:
      - uses: actions/checkout@v2
      - name: Compile RTX-32x
        uses: null511/PixelGraph.GitHubAction@main
        with:
          profile: src/BRtx-32x.pack.yml
          zip: ${{ env.release_filename }}
      - name: Release RTX-32x
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.prepare_release.outputs.upload_url }}
          asset_path: ./${{ env.release_filename }}
          asset_name: ${{ env.release_filename }}
          asset_content_type: application/zip

  publish_models_labPbr_32x:
    name: Publish Models-LabPbr-32x
    runs-on: ubuntu-latest
    needs: [prepare_release]
    env:
      release_filename: Textureless-Models-LabPbr-32x-v${{ env.GITHUB_RUN_NUMBER }}.zip
    steps:
      - uses: actions/checkout@v2
      - name: Compile Models-LabPbr-32x
        uses: null511/PixelGraph.GitHubAction@main
        with:
          profile: src-models/LabPbr-32x.pack.yml
          zip: ${{ env.release_filename }}
      - name: Release Models-LabPbr-32x
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.prepare_release.outputs.upload_url }}
          asset_path: ./${{ env.release_filename }}
          asset_name: ${{ env.release_filename }}
          asset_content_type: application/zip
      - name: Publish LabPbr-Models-32x to CurseForge
        uses: itsmeow/curseforge-upload@v3
        if: github.event.inputs.publish_curseforge == 'true'
        with:
          display_name: "LabPBR Models 32x v${{ env.GITHUB_RUN_NUMBER }}"
          file_path: "Textureless-Models-LabPbr-32x-v${{ env.GITHUB_RUN_NUMBER }}.zip"
          changelog: "###Release ${{github.event.inputs.version}}\n\nSee base Textureless release for changelog notes."
          release_type: "release"
          project_id: 469686
          game_endpoint: "minecraft"
          #game_versions: "Minecraft 1.18:1.18.1"
          game_versions: "9008,8857,8830,8516,8203,8152,8134,8056,8010,7892,7890,7675,7664,7469,7413,7361,7344,7318,7132,7107,7081"
          token: "${{ secrets.CF_API_TOKEN }}"

  publish_models_labPbr_64x:
    name: Publish Models-LabPbr-64x
    runs-on: ubuntu-latest
    needs: [prepare_release]
    env:
      release_filename: Textureless-Models-LabPbr-64x-v${{ env.GITHUB_RUN_NUMBER }}.zip
    steps:
      - uses: actions/checkout@v2
      - name: Compile Models-LabPbr-64x
        uses: null511/PixelGraph.GitHubAction@main
        with:
          profile: src-models/LabPbr-64x.pack.yml
          zip: ${{ env.release_filename }}
      - name: Release Models LabPbr 64x
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.prepare_release.outputs.upload_url }}
          asset_path: ./${{ env.release_filename }}
          asset_name: ${{ env.release_filename }}
          asset_content_type: application/zip

  publish_models_labPbr_16x:
    name: Publish Models-LabPbr-16x
    runs-on: ubuntu-latest
    needs: [prepare_release]
    env:
      release_filename: Textureless-Models-LabPbr-16x-v${{ env.GITHUB_RUN_NUMBER }}.zip
    steps:
      - uses: actions/checkout@v2
      - name: Compile Models-LabPbr-16x
        uses: null511/PixelGraph.GitHubAction@main
        with:
          profile: src-models/LabPbr-16x.pack.yml
          zip: ${{ env.release_filename }}
      - name: Release Models-LabPbr-16x
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.prepare_release.outputs.upload_url }}
          asset_path: ./${{ env.release_filename }}
          asset_name: ${{ env.release_filename }}
          asset_content_type: application/zip

  publish_models_labBakedAO_32x:
    name: Publish Models-LabBakedAO-32x
    runs-on: ubuntu-latest
    needs: [prepare_release]
    env:
      release_filename: Textureless-Models-LabBakedAO-32x-v${{ env.GITHUB_RUN_NUMBER }}.zip
    steps:
      - uses: actions/checkout@v2
      - name: Compile Models-LabBakedAO-32x
        uses: null511/PixelGraph.GitHubAction@main
        with:
          profile: src-models/LabBakedAO-32x.pack.yml
          zip: ${{ env.release_filename }}
      - name: Release Models-LabBakedAO-32x
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.prepare_release.outputs.upload_url }}
          asset_path: ./${{ env.release_filename }}
          asset_name: ${{ env.release_filename }}
          asset_content_type: application/zip

  publish_models_oldPbr_32x:
    name: Publish Models-OldPbr-32x
    runs-on: ubuntu-latest
    needs: [prepare_release]
    env:
      release_filename: Textureless-Models-OldPbr-32x-v${{ env.GITHUB_RUN_NUMBER }}.zip
    steps:
      - uses: actions/checkout@v2
      - name: Compile Models-OldPbr-32x
        uses: null511/PixelGraph.GitHubAction@main
        with:
          profile: src-models/OldPbr-32x.pack.yml
          zip: ${{ env.release_filename }}
      - name: Release Models-OldPbr-32x
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.prepare_release.outputs.upload_url }}
          asset_path: ./${{ env.release_filename }}
          asset_name: ${{ env.release_filename }}
          asset_content_type: application/zip

  publish-release:
    name: Publish Release
    runs-on: ubuntu-latest
    if: github.event.inputs.release_notes != 0
    needs:
      - prepare_release
      - publish_labPbr_32x
      - publish_labPbr_64x
      - publish_labPbr_16x
      - publish_labBakedAO_32x
      - publish_oldPbr_32x
      - publish_rtx_32x
      - publish_models_labPbr_32x
      - publish_models_labPbr_64x
      - publish_models_labPbr_16x
      - publish_models_labBakedAO_32x
      - publish_models_oldPbr_32x
    steps:
      - name: Publish Release
        uses: eregon/publish-release@v1.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ needs.prepare_release.outputs.release_id }}
