name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version Number'
        required: true

jobs:
  Publish-LabPbr-32x:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: null511/PixelGraph.GitHubAction@main
        with:
          profile: src/LabPbr-32x.pack.yml
          zip: Textureless-LabPbr-32x.zip
      - name: Upload LabPbr 32x
        uses: actions/upload-artifact@v2
        with:
          name: Textureless-LabPbr-32x
          path: Textureless-LabPbr-32x.zip

  Publish-LabPbr-64x:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: null511/PixelGraph.GitHubAction@main
        with:
          profile: src/LabPbr-64x.pack.yml
          zip: Textureless-LabPbr-64x.zip
      - name: Upload LabPbr 64x
        uses: actions/upload-artifact@v2
        with:
          name: Textureless-LabPbr-64x
          path: Textureless-LabPbr-64x.zip

  Publish-LabPbr-16x:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: null511/PixelGraph.GitHubAction@main
        with:
          profile: src/LabPbr-16x.pack.yml
          zip: Textureless-LabPbr-16x.zip
      - name: Upload LabPbr 16x
        uses: actions/upload-artifact@v2
        with:
          name: Textureless-LabPbr-16x
          path: Textureless-LabPbr-16x.zip

  Publish-LabBakedAO-32x:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: null511/PixelGraph.GitHubAction@main
        with:
          profile: src/LabBakedAO-32x.pack.yml
          zip: Textureless-LabBakedAO-32x.zip
      - name: Upload LabBakedAO 32x
        uses: actions/upload-artifact@v2
        with:
          name: Textureless-LabBakedAO-32x
          path: Textureless-LabBakedAO-32x.zip

  Publish-OldPbr-32x:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: null511/PixelGraph.GitHubAction@main
        with:
          profile: src/OldPbr-32x.pack.yml
          zip: Textureless-OldPbr-32x.zip
      - name: Upload OldPbr 32x
        uses: actions/upload-artifact@v2
        with:
          name: Textureless-OldPbr-32x
          path: Textureless-OldPbr-32x.zip

  Publish-RTX-32x:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: null511/PixelGraph.GitHubAction@main
        with:
          profile: src/BRtx-32x.pack.yml
          zip: Textureless-RTX-32x.zip
      - name: Upload RTX 32x
        uses: actions/upload-artifact@v2
        with:
          name: Textureless-RTX-32x
          path: Textureless-RTX-32x.zip

  Publish-Models-LabPbr-32x:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: null511/PixelGraph.GitHubAction@main
        with:
          profile: src-models/LabPbr-32x.pack.yml
          zip: Textureless-Models-LabPbr-32x.zip
      - name: Upload Models LabPbr 32x
        uses: actions/upload-artifact@v2
        with:
          name: Textureless-Models-LabPbr-32x
          path: Textureless-Models-LabPbr-32x.zip

  Publish-Models-LabPbr-64x:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: null511/PixelGraph.GitHubAction@main
        with:
          profile: src-models/LabPbr-64x.pack.yml
          zip: Textureless-Models-LabPbr-64x.zip
      - name: Upload Models LabPbr 64x
        uses: actions/upload-artifact@v2
        with:
          name: Textureless-Models-LabPbr-64x
          path: Textureless-Models-LabPbr-64x.zip

  Publish-Models-LabPbr-16x:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: null511/PixelGraph.GitHubAction@main
        with:
          profile: src-models/LabPbr-16x.pack.yml
          zip: Textureless-Models-LabPbr-16x.zip
      - name: Upload Models LabPbr 16x
        uses: actions/upload-artifact@v2
        with:
          name: Textureless-Models-LabPbr-16x
          path: Textureless-Models-LabPbr-16x.zip

  Publish-Models-LabBakedAO-32x:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: null511/PixelGraph.GitHubAction@main
        with:
          profile: src-models/LabBakedAO-32x.pack.yml
          zip: Textureless-Models-LabBakedAO-32x.zip
      - name: Upload Models LabBakedAO 32x
        uses: actions/upload-artifact@v2
        with:
          name: Textureless-Models-LabBakedAO-32x
          path: Textureless-Models-LabBakedAO-32x.zip

  Publish-Models-OldPbr-32x:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: null511/PixelGraph.GitHubAction@main
        with:
          profile: src-models/OldPbr-32x.pack.yml
          zip: Textureless-Models-OldPbr-32x.zip
      - name: Upload Models OldPbr 32x
        uses: actions/upload-artifact@v2
        with:
          name: Textureless-Models-OldPbr-32x
          path: Textureless-Models-OldPbr-32x.zip

  Create-Release:
    runs-on: ubuntu-latest
    needs:
      - Publish-LabPbr-32x
      - Publish-LabPbr-64x
      - Publish-LabPbr-16x
      - Publish-LabBakedAO-32x
      - Publish-OldPbr-32x
      - Publish-Models-LabPbr-32x
      - Publish-Models-LabPbr-64x
      - Publish-Models-LabPbr-16x
      - Publish-Models-LabBakedAO-32x
      - Publish-Models-OldPbr-32x
    steps:
      - name: Download LabPbr 32x
        uses: actions/download-artifact@v2
        with:
          name: Textureless-LabPbr-32x
      - name: Download LabPbr 64x
        uses: actions/download-artifact@v2
        with:
          name: Textureless-LabPbr-64x
      - name: Download LabPbr 16x
        uses: actions/download-artifact@v2
        with:
          name: Textureless-LabPbr-16x
      - name: Download LabBakedAO 32x
        uses: actions/download-artifact@v2
        with:
          name: Textureless-LabBakedAO-32x
      - name: Download OldPbr 32x
        uses: actions/download-artifact@v2
        with:
          name: Textureless-OldPbr-32x
      - name: Download RTX 32x
        uses: actions/download-artifact@v2
        with:
          name: Textureless-RTX-32x
      - name: Download Models LabPbr 32x
        uses: actions/download-artifact@v2
        with:
          name: Textureless-Models-LabPbr-32x
      - name: Download Models LabPbr 64x
        uses: actions/download-artifact@v2
        with:
          name: Textureless-Models-LabPbr-64x
      - name: Download Models LabPbr 16x
        uses: actions/download-artifact@v2
        with:
          name: Textureless-Models-LabPbr-16x
      - name: Download Models LabBakedAO 32x
        uses: actions/download-artifact@v2
        with:
          name: Textureless-Models-LabBakedAO-32x
      - name: Download Models OldPbr 32x
        uses: actions/download-artifact@v2
        with:
          name: Textureless-Models-OldPbr-32x
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.event.inputs.version }}
          release_name: Release ${{ github.event.inputs.version }}
      - name: Upload LabPbr 32x
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Textureless-LabPbr-32x.zip
          asset_name: Textureless-LabPbr-32x.zip
          asset_content_type: application/zip
      - name: Upload LabPbr 64x
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Textureless-LabPbr-64x.zip
          asset_name: Textureless-LabPbr-64x.zip
          asset_content_type: application/zip
      - name: Upload LabPbr 16x
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Textureless-LabPbr-16x.zip
          asset_name: Textureless-LabPbr-16x.zip
          asset_content_type: application/zip
      - name: Upload LabBakedAO 32x
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Textureless-LabBakedAO-32x.zip
          asset_name: Textureless-LabBakedAO-32x.zip
          asset_content_type: application/zip
      - name: Upload OldPbr 32x
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Textureless-OldPbr-32x.zip
          asset_name: Textureless-OldPbr-32x.zip
          asset_content_type: application/zip
      - name: Upload RTX 32x
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Textureless-RTX-32x.zip
          asset_name: Textureless-RTX-32x.zip
          asset_content_type: application/zip

      - name: Upload Models LabPbr 32x
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Textureless-Models-LabPbr-32x.zip
          asset_name: Textureless-Models-LabPbr-32x.zip
          asset_content_type: application/zip
      - name: Upload Models LabPbr 64x
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Textureless-Models-LabPbr-64x.zip
          asset_name: Textureless-Models-LabPbr-64x.zip
          asset_content_type: application/zip
      - name: Upload Models LabPbr 16x
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Textureless-Models-LabPbr-16x.zip
          asset_name: Textureless-Models-LabPbr-16x.zip
          asset_content_type: application/zip
      - name: Upload Models LabBakedAO 32x
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Textureless-Models-LabBakedAO-32x.zip
          asset_name: Textureless-Models-LabBakedAO-32x.zip
          asset_content_type: application/zip
      - name: Upload Models OldPbr 32x
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Textureless-Models-OldPbr-32x.zip
          asset_name: Textureless-Models-OldPbr-32x.zip
          asset_content_type: application/zip

  Upload-CurseForge:
    runs-on: ubuntu-latest
    needs: Create-Release
    steps:
      - name: Download LabPbr 32x
        uses: actions/download-artifact@v2
        with:
          name: Textureless-LabPbr-32x
      - name: Upload LabPbr 32x
        run: |
          curl -X POST \
            -F 'metadata={changelog: "Release ${{github.event.inputs.version}}", changelogType: "text", releaseType: "release", displayName: "LabPBR 32x", gameVersions: [8203]}' \
            -F 'file=@Textureless-LabPbr-32x.zip' 'https://minecraft.curseforge.com/api/projects/469686/upload-file?token=${{secrets.CF_API_TOKEN}}'
