name: Release
on:
  workflow_dispatch:
    inputs:
      release_notes:
        description: 'Release notes. (optional)'
        required: false
      publish_curseforge:
        description: 'Publish to CurseForge? true | false'
        default: 'true'
        required: false

jobs:
  prepare_release:
    name: Prepare Release
    runs-on: ubuntu-latest
    outputs:
      release_id: ${{ steps.create_release.outputs.id }}
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - run: echo -e "${{ github.event.inputs.release_notes }}" > release_notes.md
      - name: Create Release Draft
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          body_path: release_notes.md
          draft: true

  publish_labPbr_32x:
    name: Publish LabPbr-32x
    runs-on: ubuntu-latest
    needs: [prepare_release]
    env:
      release_filename: Textureless-LabPbr-32x-v${{ github.run_number }}.zip
      release_notes: ${{ github.event.inputs.release_notes }}
    steps:
      - uses: actions/checkout@v2
      - name: Compile LabPbr-32x
        uses: null511/PixelGraph.GitHubAction@main
        with:
          project: src/project.yml
          profile: Textureless-LabPbr-32x
          zip: ${{ env.release_filename }}
      - name: Release LabPbr-32x
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.prepare_release.outputs.upload_url }}
          asset_path: ./${{ env.release_filename }}
          asset_name: ${{ env.release_filename }}
          asset_content_type: application/zip
      - name: Publish LabPbr-32x to CurseForge
        uses: itsmeow/curseforge-upload@v3
        if: github.event.inputs.publish_curseforge == 'true'
        with:
          display_name: LabPBR-32x v${{ github.run_number }}
          file_path: ${{ env.release_filename }}
          changelog: "###Release ${{ github.run_number }}\n${{ github.event.inputs.release_notes }}"
          release_type: release
          project_id: 469686
          game_endpoint: minecraft
          game_versions: "9008,8857,8830,8516,8203,8152,8134,8056,8010,7892,7890,7675,7664,7469,7413,7361,7344,7318,7132,7107,7081"
          token: ${{ secrets.CF_API_TOKEN }}

  publish_labPbr_16x:
    name: Publish LabPbr-16x
    runs-on: ubuntu-latest
    needs: [prepare_release]
    env:
      release_filename: Textureless-LabPbr-16x-v${{ github.run_number }}.zip
    steps:
      - uses: actions/checkout@v2
      - name: Compile LabPbr-16x
        uses: null511/PixelGraph.GitHubAction@main
        with:
          project: src/project.yml
          profile: Textureless-LabPbr-16x
          zip: ${{ env.release_filename }}
      - name: Release LabPbr-16x
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.prepare_release.outputs.upload_url }}
          asset_path: ./${{ env.release_filename }}
          asset_name: ${{ env.release_filename }}
          asset_content_type: application/zip

  publish_oldPbr_32x:
    name: Publish OldPbr-32x
    runs-on: ubuntu-latest
    needs: [prepare_release]
    env:
      release_filename: Textureless-OldPbr-32x-v${{ github.run_number }}.zip
    steps:
      - uses: actions/checkout@v2
      - name: Compile OldPbr-32x
        uses: null511/PixelGraph.GitHubAction@main
        with:
          project: src/project.yml
          profile: Textureless-OldPbr-32x
          zip: ${{ env.release_filename }}
      - name: Release OldPbr-32x
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.prepare_release.outputs.upload_url }}
          asset_path: ./${{ env.release_filename }}
          asset_name: ${{ env.release_filename }}
          asset_content_type: application/zip

  publish_rtx_32x:
    name: Publish RTX-32x
    runs-on: ubuntu-latest
    needs: [prepare_release]
    env:
      release_filename: Textureless-RTX-32x-v${{ github.run_number }}.zip
    steps:
      - uses: actions/checkout@v2
      - name: Compile RTX-32x
        uses: null511/PixelGraph.GitHubAction@main
        with:
          project: src/project.yml
          profile: Textureless-RTX-32x
          zip: ${{ env.release_filename }}
      - name: Release RTX-32x
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.prepare_release.outputs.upload_url }}
          asset_path: ./${{ env.release_filename }}
          asset_name: ${{ env.release_filename }}
          asset_content_type: application/zip

  publish_models_labPbr_32x:
    name: Publish Models-LabPbr-32x
    runs-on: ubuntu-latest
    needs: [prepare_release]
    env:
      release_filename: Textureless-Models-LabPbr-32x-v${{ github.run_number }}.zip
    steps:
      - uses: actions/checkout@v2
      - name: Compile Models-LabPbr-32x
        uses: null511/PixelGraph.GitHubAction@main
        with:
          project: src-models/project.yml
          profile: Textureless-Models-LabPbr-32x
          zip: ${{ env.release_filename }}
      - name: Release Models-LabPbr-32x
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.prepare_release.outputs.upload_url }}
          asset_path: ./${{ env.release_filename }}
          asset_name: ${{ env.release_filename }}
          asset_content_type: application/zip
      - name: Publish LabPbr-Models-32x to CurseForge
        uses: itsmeow/curseforge-upload@v3
        if: github.event.inputs.publish_curseforge == 'true'
        with:
          display_name: LabPBR-Models-32x v${{ github.run_number }}
          file_path: ${{ env.release_filename }}
          changelog: "###Release ${{ github.run_number }}\nSee base Textureless release for changelog notes."
          release_type: release
          project_id: 582743
          game_endpoint: minecraft
          game_versions: "9008,8857,8830,8516,8203,8152,8134,8056,8010,7892,7890,7675,7664,7469,7413,7361,7344,7318,7132,7107,7081"
          token: ${{ secrets.CF_API_TOKEN }}

  publish_models_labPbr_16x:
    name: Publish Models-LabPbr-16x
    runs-on: ubuntu-latest
    needs: [prepare_release]
    env:
      release_filename: Textureless-Models-LabPbr-16x-v${{ github.run_number }}.zip
    steps:
      - uses: actions/checkout@v2
      - name: Compile Models-LabPbr-16x
        uses: null511/PixelGraph.GitHubAction@main
        with:
          project: src-models/project.yml
          profile: Textureless-Models-LabPbr-16x
          zip: ${{ env.release_filename }}
      - name: Release Models-LabPbr-16x
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.prepare_release.outputs.upload_url }}
          asset_path: ./${{ env.release_filename }}
          asset_name: ${{ env.release_filename }}
          asset_content_type: application/zip

  publish_models_oldPbr_32x:
    name: Publish Models-OldPbr-32x
    runs-on: ubuntu-latest
    needs: [prepare_release]
    env:
      release_filename: Textureless-Models-OldPbr-32x-v${{ github.run_number }}.zip
    steps:
      - uses: actions/checkout@v2
      - name: Compile Models-OldPbr-32x
        uses: null511/PixelGraph.GitHubAction@main
        with:
          project: src-models/project.yml
          profile: Textureless-Models-OldPbr-32x
          zip: ${{ env.release_filename }}
      - name: Release Models-OldPbr-32x
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.prepare_release.outputs.upload_url }}
          asset_path: ./${{ env.release_filename }}
          asset_name: ${{ env.release_filename }}
          asset_content_type: application/zip

  publish_create_labPbr_32x:
    name: Publish Create-LabPbr-32x
    runs-on: ubuntu-latest
    needs: [prepare_release]
    env:
      release_filename: Textureless-Create-LabPbr-32x-v${{ github.run_number }}.zip
    steps:
      - uses: actions/checkout@v2
      - name: Compile Create-LabPbr-32x
        uses: null511/PixelGraph.GitHubAction@main
        with:
          project: src-create/project.yml
          profile: Textureless-Create-LabPbr-32x
          zip: ${{ env.release_filename }}
      - name: Release Create-LabPbr-32x
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.prepare_release.outputs.upload_url }}
          asset_path: ./${{ env.release_filename }}
          asset_name: ${{ env.release_filename }}
          asset_content_type: application/zip
      # - name: Publish LabPbr-Create-32x to CurseForge
      #   uses: itsmeow/curseforge-upload@v3
      #   if: github.event.inputs.publish_curseforge == 'true'
      #   with:
      #     display_name: LabPBR-Create-32x v${{ github.run_number }}
      #     file_path: ${{ env.release_filename }}
      #     changelog: "###Release ${{ github.run_number }}\nSee base Textureless release for changelog notes."
      #     release_type: release
      #     project_id: ?
      #     game_endpoint: minecraft
      #     game_versions: "9008,8857,8830,8516,8203,8152,8134,8056,8010,7892,7890,7675,7664,7469,7413,7361,7344,7318,7132,7107,7081"
      #     token: ${{ secrets.CF_API_TOKEN }}

  publish_create_oldPbr_32x:
    name: Publish Create-OldPbr-32x
    runs-on: ubuntu-latest
    needs: [prepare_release]
    env:
      release_filename: Textureless-Create-OldPbr-32x-v${{ github.run_number }}.zip
    steps:
      - uses: actions/checkout@v2
      - name: Compile Create-OldPbr-32x
        uses: null511/PixelGraph.GitHubAction@main
        with:
          project: src-create/project.yml
          profile: Textureless-Create-OldPbr-32x
          zip: ${{ env.release_filename }}
      - name: Release Create-LabPbr-32x
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.prepare_release.outputs.upload_url }}
          asset_path: ./${{ env.release_filename }}
          asset_name: ${{ env.release_filename }}
          asset_content_type: application/zip

  publish-release:
    name: Publish Release
    runs-on: ubuntu-latest
    if: github.event.inputs.release_notes != 0
    needs:
      - prepare_release
      - publish_labPbr_32x
      - publish_labPbr_16x
      - publish_oldPbr_32x
      - publish_rtx_32x
      - publish_models_labPbr_32x
      - publish_models_labPbr_16x
      - publish_models_oldPbr_32x
      - publish_create_labPbr_32x
    steps:
      - name: Publish Release
        uses: eregon/publish-release@v1.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ needs.prepare_release.outputs.release_id }}
